### ISSUE TITLE
How to retrieve only published entries.

### ISSUE THREAD

**Issue by jyaunches** [contentful/contentful.swift#181] opened 2018-03-16 16:58 UTC
Fill in the following details, then delete this line before submitting. (To mark a checkbox change `- [ ]` to `- [x]`).
> - contentful.swift version number: 1.0.1
> - Xcode version number: 9.2
> - Target operating system(s) and version number(s)
    - [ x] iOS: 
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [ ] Carthage
    - [ x] Cocoapods

Apologies if this isn't the place. I'm not sure if it's a bug or not.. Should I be receiving entries that aren't published when I query for them? If so, how do I say that I only want ones that have been published? Or I'd be happy to just receive a state of 'published' or 'unpublished'.

Just to clarify.. I **AM** receiving entries that I've 'unpublished' through the contentful CMS interface. And I have no way of determining their published status.

Pretty basic code:

![screen shot 2018-03-16 at 12 56 23 pm](https://user-images.githubusercontent.com/372490/37533853-7cf12536-2919-11e8-99b6-3d0ab505ce7e.png)

**Comment by loudmouth** [comment] 2018-03-16 17:35
Hi @jyaunches 

Yikes! You should absolutely not be receiving unpublished entries while connected to the Content Delivery API [CDA]—the code you shared shows that you did not specify that you wanted to interface with the Content Preview API [CPA] and when interfacing with CDA you should only ever be receiving published entries. One comment is that sometimes it can take 5-10 seconds for a publish/unpublish action to propagate to our CDN servers which are distributed across the globe, so if you're unpublishing and then immediately refreshing in your app, this could be the reason.

If the issue isn't to do with the propagation delay, I would be quite shocked as I've never heard of anybody receiving unpublished entries via the CDA.

I suggest opening a support request at support.contentful.com as if this is happening, it's an issue on the backend rather than an issue with the contentful.swift SDK.

I'll close this for now. Good luck!

**Closed by loudmouth** 2018-03-16 17:35 UTC
