### ISSUE TITLE
Unresolved link not mapping to Entry - Link.Entry = nil 

### ISSUE THREAD

**Issue by vish-sharma1** [contentful/contentful.swift#259] opened 2019-04-01 21:49 UTC
- contentful.swift version number: 4.2.4
- Xcode version number: 10.1
- Target operating system(s) and version number(s)
  - [x] iOS: 
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [ ] Carthage
  - [x] Cocoapods 

Hi Contentful team, 
I'm facing an issue to map "Link" object with corresponding "Entry". "FetchArray" does returns "Unresolved" type of link object with id = "Some id string", linkType = "Entry", type = "Link". However, when I try to access the related Entry - using Link.Entry it always returns nil.

I am using EntryDecodable, FieldKeysQueryable protocols and mapping my key as following:
Definition - var testLink: Link?
Required init - self.testLinkObject = try fields.decodeIfPresent(Link.self, forKey: .testLink)

I am trying to fetch entry object as following: if let testEntry = testObject.entry -> Nil. It seems my link object is not able to map with Entry id. Any advise will be helpful. Thanks

**Comment by leoneparise** [comment] 2019-04-12 23:01
Hi @vish-sharma1 I did some debugging this week and I couldn't reproduce this issue. Maybe you're using the wrong method to decode the object. Here is a sample object with links and the correct way to resolve the model.

```swift
import Foundation
import Contentful

class Course: EntryDecodable, Resource, FieldKeysQueryable, StatefulResource {

    static let contentTypeId = "course"

    let sys: Sys

    let title: String
    let slug: String
    let shortDescription: String?
    let courseDescription: String?
    let duration: Int?
    let skillLevel: String?

    var imageAsset: Asset?
    var lessons: [Lesson]?

    var hasLessons: Bool {
        return lessons != nil && lessons!.count > 0
    }
    var categories: [Category]?

    var state = ResourceState.upToDate

    required init(from decoder: Decoder) throws {
        sys                 = try decoder.sys()
        let fields          = try decoder.contentfulFieldsContainer(keyedBy: FieldKeys.self)
        title               = try fields.decode(String.self, forKey: .title)
        slug                = try fields.decode(String.self, forKey: .slug)
        shortDescription    = try fields.decodeIfPresent(String.self, forKey: .shortDescription)
        courseDescription   = try fields.decodeIfPresent(String.self, forKey: .courseDescription)
        duration            = try fields.decodeIfPresent(Int.self, forKey: .duration)
        skillLevel          = try fields.decodeIfPresent(String.self, forKey: .skillLevel)

        try fields.resolveLink(forKey: .imageAsset, decoder: decoder) { [weak self] asset in
            self?.imageAsset = asset as? Asset
        }
        try fields.resolveLinksArray(forKey: .lessons, decoder: decoder) { [weak self] array in
            self?.lessons = array as? [Lesson]
        }
        try fields.resolveLinksArray(forKey: .categories, decoder: decoder) { [weak self] array in
            self?.categories = array as? [Category]
        }
    }

    enum FieldKeys: String, CodingKey {
        case title, slug, shortDescription, duration, skillLevel, lessons, categories
        case imageAsset = "image"
        case courseDescription = "description"
    }
}
```

As you can see, you need to use the method `fields.resolveLink` instead of ` fields.decodeIfPresent`. Please, try to change the method and let me know if it works. If not, can you provide the implementation of your model so we can check it out?

**Comment by FitzAfful** [comment] 2019-06-20 06:09
Hi. Can you post a sample of either your Category or Lesson? I have a similar structure but after resolving, it's always null

**Comment by vincentvillalta** [comment] 2020-03-31 18:01
Faced this issue today, are you passing all the `contentTypeClasses` to the client initialization?

i.e. 

`let contentful = Client(spaceId: "spaceId", accessToken: "your-access-token", contentTypeClasses: [
        Category.self,
        Course.self,
        Lesson.self
    ])`

**Comment by basememara** [comment] 2020-04-21 18:59
Also be sure to add Include parameter to the query. Wasted a couple days on it since default is 1.. should really be upfront in the readme.

https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/links/retrieval-of-linked-items

**Comment by tomkowz** [comment] 2020-06-02 12:17
@vish-sharma1 is this still a valid issue?

**Comment by tomkowz** [comment] 2020-06-04 12:38
Closing this one as there is no update and the issue is 1 year old without answer.

**Closed by tomkowz** 2020-06-04 12:38 UTC
